Add dependency to sqlite3
email-utilities.h from email-common-use exports sqlite3.h (from email-storage.h)
but it doesn't have dependency to sqlite3

[  113s] In file included from /home/abuild/rpmbuild/BUILD/email-service-0.10.102/email-common-use/include/email-utilities.h:35:0,
[  113s]                  from /home/abuild/rpmbuild/BUILD/email-service-0.10.102/email-common-use/email-utilities.c:45:
[  113s] /home/abuild/rpmbuild/BUILD/email-service-0.10.102/email-core/email-storage/include/email-storage.h:41:21: fatal error: sqlite3.h: No such file or directory
[  113s]  #include <sqlite3.h>

Change-Id: I45fa7bd66e35929dd605efc8a9306d4ccb90dfd0
Signed-off-by: Sangyoon Jang <s89.jang@samsung.com>